/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Anchor: typeof import('./../src/components/Global/Anchor.vue')['default']
    Breadcrumb: typeof import('./../src/components/Page/navbar/Breadcrumb.vue')['default']
    ButtonCreate: typeof import('./../src/components/Botton/ButtonCreate.vue')['default']
    ButtonGroupPermission: typeof import('./../src/components/Botton/ButtonGroupPermission.vue')['default']
    ButtonTipPermission: typeof import('./../src/components/Botton/ButtonTipPermission.vue')['default']
    CascaderNest: typeof import('./../src/components/Select/CascaderNest.vue')['default']
    CascaderNestMutiple: typeof import('./../src/components/Select/CascaderNestMutiple.vue')['default']
    DefaultTable: typeof import('./../src/components/Table/DefaultTable.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FooterFormManage: typeof import('./../src/components/Footer/FooterFormManage.vue')['default']
    FormLogin: typeof import('./../src/components/Form/FormLogin.vue')['default']
    FormManage: typeof import('./../src/components/Form/FormManage.vue')['default']
    FullScreen: typeof import('./../src/components/Page/navbar/FullScreen.vue')['default']
    HistoryLink: typeof import('./../src/components/Page/HistoryLink.vue')['default']
    Menu: typeof import('./../src/components/Page/Menu.vue')['default']
    NavBar: typeof import('./../src/components/Page/NavBar.vue')['default']
    PickerDate: typeof import('./../src/components/Picker/PickerDate.vue')['default']
    PickerDateRange: typeof import('./../src/components/Picker/PickerDateRange.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectRole: typeof import('./../src/components/Select/SelectRole.vue')['default']
    SvgIcon: typeof import('./../src/components/Global/SvgIcon.vue')['default']
    TableCellLink: typeof import('./../src/components/Table/TableCellLink.vue')['default']
    TagStatus: typeof import('./../src/components/tag/TagStatus.vue')['default']
    ThemeSetting: typeof import('./../src/components/Page/navbar/ThemeSetting.vue')['default']
    UploadImage: typeof import('./../src/components/upload/UploadImage.vue')['default']
    UserInfo: typeof import('./../src/components/Page/navbar/UserInfo.vue')['default']
  }
}
